### ISSUE TITLE
RSpec: Some tests are failing

### ISSUE THREAD

**Issue by perlun** [matadon/mizuno#50]
Using JRuby 1.7.25 on the latest commit (506beb09571f0398d5851366d3c9779c14b061fb), this is what I get:

```
*..*.FFFFFFFFF******..****FFFFFFFF.FFFFFFF.FFFFFFFFF

Pending:
  Mizuno::Client times out when the server doesn't respond
    # Not Yet Implemented
    # ./spec/client_spec.rb:6
  Mizuno::Client makes https requests to google
    # Not Yet Implemented
    # ./spec/client_spec.rb:49
  daemonization handles ssl requests
    # Not Yet Implemented
    # ./spec/daemonization_spec.rb:210
  daemonization handles spdy requests
    # Not Yet Implemented
    # ./spec/daemonization_spec.rb:213
  daemonization writes server logs to a file
    # Not Yet Implemented
    # ./spec/daemonization_spec.rb:216
  daemonization allows for rotation of server logs
    # Not Yet Implemented
    # ./spec/daemonization_spec.rb:219
  daemonization switches to a different group
    # Not Yet Implemented
    # ./spec/daemonization_spec.rb:222
  daemonization switches to a different user
    # Not Yet Implemented
    # ./spec/daemonization_spec.rb:227
  rails support sets the environment for rails
    # Not Yet Implemented
    # ./spec/mizuno_rails_spec.rb:4
  rails support runs in development mode
    # Not Yet Implemented
    # ./spec/mizuno_rails_spec.rb:7
  rails support runs in production mode
    # Not Yet Implemented
    # ./spec/mizuno_rails_spec.rb:10
  rails support serves up static assets in production mode
    # Not Yet Implemented
    # ./spec/mizuno_rails_spec.rb:13

Failures:

  1) daemonization starts from a rackup file without daemonizing
     Failure/Error: expect(daemon).to be_online
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/command_line_spec.rb:98:in `(root)'

  2) daemonization starts and stops
     Failure/Error: expect(daemon).to be_online
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:117:in `(root)'

  3) daemonization starts as a daemon even if the root is a 404
     Failure/Error: expect(daemon).to be_online
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:124:in `(root)'

  4) daemonization starts as a daemon even if the root is a 301
     Failure/Error: expect(daemon).to be_online
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:132:in `(root)'

  5) daemonization fails to start start if the root is a 500
     Failure/Error: expect(daemon).to be_offline
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:140:in `(root)'

  6) daemonization reloads on SIGHUP only if app has been updated
     Failure/Error: expect(daemon).to be_online
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:145:in `(root)'

  7) daemonization reloads when a trigger file is touched
     Failure/Error: expect(daemon).to be_online
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:165:in `(root)'

  8) daemonization reloads from the command line
     Failure/Error: expect(daemon).to be_online
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:185:in `(root)'

  9) daemonization starts a new server if asked to reload one that isn't running
     Failure/Error: expect(daemon).to be_offline
     ArgumentError:
       wrong number of arguments calling `expect` (1 for 0)
     # ./spec/daemonization_spec.rb:204:in `(root)'

  10) Java::OrgJrubyRackServlet::RewindableInputStream should read data byte by byte
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/rewindable_input_stream_spec.rb:13)

  11) Java::OrgJrubyRackServlet::RewindableInputStream should read data then rewind and read again (in memory)
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/rewindable_input_stream_spec.rb:13)

  12) Java::OrgJrubyRackServlet::RewindableInputStream should read data then rewind and read again (temp file)
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/rewindable_input_stream_spec.rb:13)

  13) Java::OrgJrubyRackServlet::RewindableInputStream should read incomplete data rewind and read until end
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/rewindable_input_stream_spec.rb:13)

  14) Java::OrgJrubyRackServlet::RewindableInputStream should rewind unread data
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/rewindable_input_stream_spec.rb:13)

  15) Java::OrgJrubyRackServlet::RewindableInputStream should mark and reset
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/rewindable_input_stream_spec.rb:13)

  16) Java::OrgJrubyRackServlet::RewindableInputStream should read data then rewind and read again (server)
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/rewindable_input_stream_spec.rb:13)

  17) Mizuno::Server https
     Failure/Error: Unable to find matching line from backtrace
     Java::JavaNet::BindException:
       Address already in use
     # sun.nio.ch.Net.bind0(Native Method)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:433)
     # sun.nio.ch.Net.bind(sun/nio/ch/Net.java:425)
     # sun.nio.ch.ServerSocketChannelImpl.bind(sun/nio/ch/ServerSocketChannelImpl.java:223)
     # sun.nio.ch.ServerSocketAdaptor.bind(sun/nio/ch/ServerSocketAdaptor.java:74)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.open(org/eclipse/jetty/server/nio/SelectChannelConnector.java:187)
     # org.eclipse.jetty.server.AbstractConnector.doStart(org/eclipse/jetty/server/AbstractConnector.java:316)
     # org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(org/eclipse/jetty/server/nio/SelectChannelConnector.java:265)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # org.eclipse.jetty.server.Server.doStart(org/eclipse/jetty/server/Server.java:293)
     # org.eclipse.jetty.util.component.AbstractLifeCycle.start(org/eclipse/jetty/util/component/AbstractLifeCycle.java:64)
     # java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
     # RUBY.run(./lib/mizuno/server.rb:108)
     # RUBY.run(./lib/mizuno/server.rb:31)
     # RUBY.run(./lib/mizuno/server.rb:28)
     # RUBY.(root)(./spec/server_spec.rb:181)

  18) Mizuno::Server http 403 FORBIDDEN
     Failure/Error: response.code.should == "403"
       expected: "403"
            got: "200" (using ==)
     # ./spec/server_spec.rb:26:in `(root)'

  19) Mizuno::Server http 404 NOT FOUND
     Failure/Error: response.code.should == "404"
       expected: "404"
            got: "200" (using ==)
     # ./spec/server_spec.rb:31:in `(root)'

  20) Mizuno::Server http rack headers
     Failure/Error: content = JSON.parse(response.body)
     JSON::ParserError:
       source 'OK' not in JSON!
     # ./spec/server_spec.rb:37:in `(root)'

  21) Mizuno::Server http form variables via GET
     Failure/Error: content = JSON.parse(response.body)
     JSON::ParserError:
       source 'OK' not in JSON!
     # ./spec/server_spec.rb:47:in `(root)'

  22) Mizuno::Server http form variables via POST
     Failure/Error: content = JSON.parse(response.body)
     JSON::ParserError:
       source 'OK' not in JSON!
     # ./spec/server_spec.rb:55:in `(root)'

  23) Mizuno::Server http custom headers
     Failure/Error: content = JSON.parse(response.body)
     JSON::ParserError:
       source 'OK' not in JSON!
     # ./spec/server_spec.rb:62:in `(root)'

  24) Mizuno::Server http rack.java.servlet
     Failure/Error: content = JSON.parse(response.body)
     JSON::ParserError:
       source 'OK' not in JSON!
     # ./spec/server_spec.rb:69:in `(root)'

  25) Mizuno::Server http server port and hostname
     Failure/Error: content = JSON.parse(response.body)
     JSON::ParserError:
       source 'OK' not in JSON!
     # ./spec/server_spec.rb:80:in `(root)'

  26) Mizuno::Server http uri scheme
     Failure/Error: content = JSON.parse(response.body)
     JSON::ParserError:
       source 'OK' not in JSON!
     # ./spec/server_spec.rb:87:in `(root)'

  27) Mizuno::Server http file downloads
     Failure/Error: response["Content-Type"].should == "image/png"
       expected: "image/png"
            got: "text/plain" (using ==)
     # ./spec/server_spec.rb:94:in `(root)'

  28) Mizuno::Server http file uploads
     Failure/Error: response.body.should == "8da4b60a9bbe205d4d3699985470627e"
       expected: "8da4b60a9bbe205d4d3699985470627e"
            got: "OK" (using ==)
     # ./spec/server_spec.rb:118:in `(root)'

  29) Mizuno::Server http async requests
     Failure/Error: lock.synchronize { buffer.should be_empty }
       expected empty? to return true, got false
     # ./spec/server_spec.rb:136:in `(root)'
     # ./spec/server_spec.rb:136:in `(root)'

  30) Mizuno::Server http streaming response
     Failure/Error: chunks.should == ["one", "two"]
       expected: ["one", "two"]
            got: ["OK"] (using ==)
       Diff:
       @@ -1,2 +1,2 @@
       -["one", "two"]
       +["OK"]
     # ./spec/server_spec.rb:158:in `(root)'

  31) Mizuno::Server http doesn't double-chunk content
     Failure/Error: response.should be_chunked
       expected chunked? to return true, got false
     # ./spec/server_spec.rb:164:in `(root)'

  32) Mizuno::Server http doesn't double-chunk rails-like content
     Failure/Error: response.should be_chunked
       expected chunked? to return true, got false
     # ./spec/server_spec.rb:170:in `(root)'

  33) Mizuno::Server http sets multiple cookies correctly
     Failure/Error: response["set-cookie"].should == "first=one+fish, second=two+fish"
       expected: "first=one+fish, second=two+fish"
            got: nil (using ==)
     # ./spec/server_spec.rb:176:in `(root)'

Finished in 18.53 seconds
52 examples, 33 failures, 12 pending

Failed examples:

rspec ./spec/command_line_spec.rb:96 # daemonization starts from a rackup file without daemonizing
rspec ./spec/daemonization_spec.rb:115 # daemonization starts and stops
rspec ./spec/daemonization_spec.rb:122 # daemonization starts as a daemon even if the root is a 404
rspec ./spec/daemonization_spec.rb:130 # daemonization starts as a daemon even if the root is a 301
rspec ./spec/daemonization_spec.rb:138 # daemonization fails to start start if the root is a 500
rspec ./spec/daemonization_spec.rb:143 # daemonization reloads on SIGHUP only if app has been updated
rspec ./spec/daemonization_spec.rb:163 # daemonization reloads when a trigger file is touched
rspec ./spec/daemonization_spec.rb:183 # daemonization reloads from the command line
rspec ./spec/daemonization_spec.rb:203 # daemonization starts a new server if asked to reload one that isn't running
rspec ./spec/rewindable_input_stream_spec.rb:21 # Java::OrgJrubyRackServlet::RewindableInputStream should read data byte by byte
rspec ./spec/rewindable_input_stream_spec.rb:28 # Java::OrgJrubyRackServlet::RewindableInputStream should read data then rewind and read again (in memory)
rspec ./spec/rewindable_input_stream_spec.rb:34 # Java::OrgJrubyRackServlet::RewindableInputStream should read data then rewind and read again (temp file)
rspec ./spec/rewindable_input_stream_spec.rb:40 # Java::OrgJrubyRackServlet::RewindableInputStream should read incomplete data rewind and read until end
rspec ./spec/rewindable_input_stream_spec.rb:60 # Java::OrgJrubyRackServlet::RewindableInputStream should rewind unread data
rspec ./spec/rewindable_input_stream_spec.rb:72 # Java::OrgJrubyRackServlet::RewindableInputStream should mark and reset
rspec ./spec/rewindable_input_stream_spec.rb:90 # Java::OrgJrubyRackServlet::RewindableInputStream should read data then rewind and read again (server)
rspec ./spec/server_spec.rb:180 # Mizuno::Server https
rspec ./spec/server_spec.rb:24 # Mizuno::Server http 403 FORBIDDEN
rspec ./spec/server_spec.rb:29 # Mizuno::Server http 404 NOT FOUND
rspec ./spec/server_spec.rb:34 # Mizuno::Server http rack headers
rspec ./spec/server_spec.rb:44 # Mizuno::Server http form variables via GET
rspec ./spec/server_spec.rb:51 # Mizuno::Server http form variables via POST
rspec ./spec/server_spec.rb:59 # Mizuno::Server http custom headers
rspec ./spec/server_spec.rb:66 # Mizuno::Server http rack.java.servlet
rspec ./spec/server_spec.rb:78 # Mizuno::Server http server port and hostname
rspec ./spec/server_spec.rb:85 # Mizuno::Server http uri scheme
rspec ./spec/server_spec.rb:91 # Mizuno::Server http file downloads
rspec ./spec/server_spec.rb:101 # Mizuno::Server http file uploads
rspec ./spec/server_spec.rb:121 # Mizuno::Server http async requests
rspec ./spec/server_spec.rb:147 # Mizuno::Server http streaming response
rspec ./spec/server_spec.rb:162 # Mizuno::Server http doesn't double-chunk content
rspec ./spec/server_spec.rb:168 # Mizuno::Server http doesn't double-chunk rails-like content
rspec ./spec/server_spec.rb:174 # Mizuno::Server http sets multiple cookies correctly
```

My Gemfile.lock:

```
PATH
  remote: .
  specs:
    mizuno (0.6.11)
      childprocess (>= 0.2.6)
      choice (>= 0.1.0)
      ffi (>= 1.0.0)
      rack (>= 1.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    childprocess (0.5.9)
      ffi (~> 1.0, >= 1.0.11)
    choice (0.2.0)
    diff-lcs (1.1.3)
    ffi (1.9.10-java)
    json_pure (1.8.3)
    mini_portile2 (2.0.0)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    nokogiri (1.6.7.2-java)
    rack (1.6.4)
    rake (11.1.2)
    rspec (2.7.0)
      rspec-core (~> 2.7.0)
      rspec-expectations (~> 2.7.0)
      rspec-mocks (~> 2.7.0)
    rspec-core (2.7.1)
    rspec-expectations (2.7.0)
      diff-lcs (~> 1.1.2)
    rspec-mocks (2.7.0)

PLATFORMS
  java
  ruby

DEPENDENCIES
  json_pure (>= 1.6.0)
  mizuno!
  nokogiri
  rake
  rspec (>= 2.7.0)
  rspec-core (>= 2.7.0)

BUNDLED WITH
   1.12.4
```

**Comment by perlun** [comment]
Unsure if this is a problem anymore, have switched away from Mizuno to Puma personally. Closing.
